
<!DOCTYPE html>
<html>
<head>
<title></title>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--------*CSS files*--------->
  <!--font-awesome-->
  <link rel="stylesheet" href="assets/fontawesome-icons/all.css">
  <link rel="stylesheet" href="assets/fonts/font.css">
  <!--google fonts-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;1,600;1,700&display=swap" rel="stylesheet">
  <!--Bootstrap-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <style>
      body{
          background-color:#e2e2e2;
      }
      .autogenerate{
          text-align:center;
      }
  </style>
  </head>
<body>
    <div class="container" style="background:#fff;width:800px;height:600px;margin-top:20px;font-size:16px;font-family:Poppins,sans-seriff;padding:25px;border-radius:10px;border-color:#800000;border-width:4px 1px;border-style:solid">
    <div class="content">
    <br/><p>Hi {TO_NAME},</p>

<p>Welcome to AiBuddhi! We’re excited that you are exploring opportunities at Aibuddhi and that you have created your account. As a reminder, you created your profile with email address {TO_EMAIL}. Please continue using this sign in option when visiting the site.</p>

<p>What Next?</p>
<p>We encourage you to complete your application – it’s the first step in getting to know you!Please attach your resume, add your education, experiences and interests.</p>

<p>We hope you’ll take some time to explore our website and our other social media platforms. Our team will review your application and get back to you shortly</p>

<p>Thank you,</p>

<p>AiBuddhi Recruiting Team</p><br/>
    </div>
    </div>
    <div class="autogenerate content">
    <h5>

    <p>This is an autogenerated email. Please do not reply.The information contained in this e-mail are intended for the exclusive use of the addressee(s) and may contain confidential or privileged information.</p>
    </h5>
    </div>
        
<script src="assets/fontawesome-icons/all.js"></script>
<!--jQuery file-->
<script src="assets/jquery/jquery-3.5.1.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<!--Bootstrap file-->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>  
</body>
</html>

